# Generated by Django 5.2.7 on 2025-10-29 05:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('minimum_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discount Scheme',
                'verbose_name_plural': 'Discount Schemes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('minimum_quantity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Rule',
                'verbose_name_plural': 'Pricing Rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Category code (e.g., SOLATE-GEN)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Category name (e.g., Soil - Laboratory tests)', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Test Category',
                'verbose_name_plural': 'Test Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subcategory name (e.g., Physical Properties:)', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='pricing.testcategory')),
            ],
            options={
                'verbose_name': 'Test Subcategory',
                'verbose_name_plural': 'Test Subcategories',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_code', models.CharField(help_text='Unique system code (e.g., SOIL-PHPR-001)', max_length=50, unique=True)),
                ('display_code', models.CharField(help_text='Display code (e.g., SL-GSD)', max_length=20)),
                ('test_name', models.CharField(help_text='Full test name', max_length=300)),
                ('method_standard', models.CharField(help_text='Testing method or standard', max_length=200)),
                ('unit', models.CharField(help_text='Pricing unit (e.g., per sample, per meter)', max_length=50)),
                ('currency', models.CharField(choices=[('UGX', 'Ugandan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='UGX', max_length=3)),
                ('price', models.DecimalField(decimal_places=2, help_text='Test price', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tat_days', models.PositiveIntegerField(help_text='Turnaround time in days')),
                ('sample_type', models.CharField(choices=[('Soil', 'Soil'), ('Rocks', 'Rocks'), ('Concrete', 'Concrete'), ('Steel', 'Steel'), ('Water', 'Water'), ('Other', 'Other')], default='Soil', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Additional requirements or notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_items', to='pricing.testcategory')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_items', to='pricing.testsubcategory')),
            ],
            options={
                'verbose_name': 'Test Item',
                'verbose_name_plural': 'Test Items',
                'ordering': ['category', 'subcategory', 'test_name'],
                'indexes': [models.Index(fields=['system_code'], name='pricing_tes_system__2e916f_idx'), models.Index(fields=['display_code'], name='pricing_tes_display_713795_idx'), models.Index(fields=['category', 'subcategory'], name='pricing_tes_categor_c236a7_idx'), models.Index(fields=['is_active'], name='pricing_tes_is_acti_fe7be9_idx')],
            },
        ),
    ]
