# Generated by Django 5.2.7 on 2025-10-29 05:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Client or company name', max_length=200)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('company_registration', models.CharField(blank=True, help_text='Company registration number', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(help_text='Unique sample identifier', max_length=50, unique=True)),
                ('client_reference', models.CharField(blank=True, help_text="Client's reference number", max_length=100)),
                ('sample_type', models.CharField(help_text='Type of sample (e.g., Soil, Concrete, Steel)', max_length=100)),
                ('sample_description', models.TextField(help_text='Detailed description of the sample')),
                ('sample_condition', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('insufficient', 'Insufficient'), ('contaminated', 'Contaminated')], default='good', max_length=20)),
                ('quantity', models.CharField(help_text='Quantity or amount of sample', max_length=100)),
                ('location_collected', models.CharField(blank=True, help_text='Location where sample was collected', max_length=200)),
                ('collection_date', models.DateField(blank=True, help_text='Date sample was collected', null=True)),
                ('received_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('rush', 'Rush')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_progress', 'In Progress'), ('testing', 'Testing'), ('completed', 'Completed'), ('reported', 'Reported'), ('cancelled', 'Cancelled')], default='received', max_length=20)),
                ('special_instructions', models.TextField(blank=True, help_text='Special instructions for testing')),
                ('delivery_method', models.CharField(blank=True, help_text='How sample was delivered', max_length=100)),
                ('courier_details', models.CharField(blank=True, help_text='Courier or delivery details', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='operations.client')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sample',
                'verbose_name_plural': 'Samples',
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='SampleAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sample_attachments/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='operations.sample')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sample Attachment',
                'verbose_name_plural': 'Sample Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='operations.sample')),
            ],
            options={
                'verbose_name': 'Sample Status History',
                'verbose_name_plural': 'Sample Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField(default=1, help_text='Number of tests requested')),
                ('special_requirements', models.TextField(blank=True, help_text='Special requirements for this test')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('test_results', models.TextField(blank=True, help_text='Test results')),
                ('test_report', models.FileField(blank=True, null=True, upload_to='test_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tests', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.sample')),
                ('test_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.testitem')),
            ],
            options={
                'verbose_name': 'Sample Test',
                'verbose_name_plural': 'Sample Tests',
                'ordering': ['test_item__category', 'test_item__test_name'],
                'unique_together': {('sample', 'test_item')},
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='requested_tests',
            field=models.ManyToManyField(related_name='samples', through='operations.SampleTest', to='pricing.testitem'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['sample_id'], name='operations__sample__ed7994_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['status'], name='operations__status_8641f4_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['received_date'], name='operations__receive_99e5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['client'], name='operations__client__fee54d_idx'),
        ),
    ]
