# Generated by Django 5.2.7 on 2025-11-01 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(help_text='Unique job identifier', max_length=50, unique=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('rush', 'Rush')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('assigned_date', models.DateTimeField(blank=True, help_text='When job was assigned to technician', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Expected completion date', null=True)),
                ('started_date', models.DateTimeField(blank=True, help_text='When technician started work', null=True)),
                ('completed_date', models.DateTimeField(blank=True, help_text='When job was completed', null=True)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for the technician')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_tests', models.ManyToManyField(help_text='Specific tests assigned in this job', related_name='jobs', to='operations.sampletest')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Technician assigned to this job', limit_choices_to={'role': 'technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created this job', on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='operations.sample')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_id'], name='operations__job_id_ae5f99_idx'), models.Index(fields=['status'], name='operations__status_a8a283_idx'), models.Index(fields=['assigned_to'], name='operations__assigne_9dbec6_idx'), models.Index(fields=['due_date'], name='operations__due_dat_7967c4_idx')],
            },
        ),
    ]
