# Generated by Django 5.2.7 on 2025-11-03 14:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleReceiptForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(help_text='Auto-generated receipt number (e.g., SRF-2025-0012)', max_length=50, unique=True)),
                ('receipt_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time samples were received')),
                ('received_by_signature', models.TextField(blank=True, help_text='Signature of lab representative')),
                ('received_by_name', models.CharField(blank=True, help_text='Name of lab representative', max_length=200)),
                ('delivered_by', models.CharField(blank=True, help_text='Client representative who delivered samples', max_length=200)),
                ('delivered_by_signature', models.TextField(blank=True, help_text='Signature of client representative')),
                ('delivered_by_name', models.CharField(blank=True, help_text='Name of client representative', max_length=200)),
                ('project_reference', models.CharField(blank=True, help_text='Project or site reference', max_length=200)),
                ('condition_notes', models.TextField(blank=True, help_text='Notes about sample condition upon receipt')),
                ('special_instructions', models.TextField(blank=True, help_text='Any special instructions or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_signed', models.BooleanField(default=False, help_text='Whether both parties have signed')),
                ('pdf_generated', models.BooleanField(default=False, help_text='Whether PDF has been generated')),
                ('received_by', models.ForeignKey(help_text='Lab staff member who received the samples', on_delete=django.db.models.deletion.CASCADE, related_name='created_receipts', to=settings.AUTH_USER_MODEL)),
                ('samples', models.ManyToManyField(help_text='Samples included in this receipt', related_name='receipt_forms', to='operations.sample')),
            ],
            options={
                'verbose_name': 'Sample Receipt Form',
                'verbose_name_plural': 'Sample Receipt Forms',
                'ordering': ['-receipt_date'],
                'indexes': [models.Index(fields=['receipt_number'], name='operations__receipt_a76a56_idx'), models.Index(fields=['receipt_date'], name='operations__receipt_6a32e4_idx'), models.Index(fields=['received_by'], name='operations__receive_08ae82_idx')],
            },
        ),
    ]
